kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-api-server-cert
  namespace: hcp
spec:
  accessModes:
    - ReadWriteMany
  #volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: apiserver
  selector:
    matchLabels:
      app: apiserver


