apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata: 
  name: "clusterregister.hcp.k8s.io"
spec: 
  group: "hcp.k8s.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "clusterregister"
    singular: "clusterregister"
    kind: "ClusterRegister"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["platform", "clustername", "region"]
          properties:
            platform:
              type: "string"
              minimum: 1
            resourcegroup:
              type: "string"
              minimum: 1
            projectid:
              type: "string"
              minimum: 1
            clustername:
              type: "string"
              minimum: 1
            region:
              type: "string"
              minimum: 1


