apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: kubefedclusters.core.kubefed.io
  resourceVersion: "1240797"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/kubefedclusters.core.kubefed.io
spec:
  conversion:
    strategy: None
  group: core.kubefed.io
  names:
    kind: KubeFedCluster
    listKind: KubeFedClusterList
    plural: kubefedclusters
    singular: kubefedcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: ready
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              apiEndpoint:
                type: string
              caBundle:
                format: byte
                type: string
              disabledTLSValidations:
                items:
                  type: string
                type: array
              proxyURL:
                type: string
              secretRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - apiEndpoint
            - secretRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastProbeTime
                  - status
                  - type
                  type: object
                type: array
              region:
                type: string
              zones:
                items:
                  type: string
                type: array
            required:
            - conditions
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
